<?php

/**
 * @file
 * event_finder_api module
 */


/*
 * Implements hook_views_pre_render().
 */
function event_finder_api_views_pre_render(&$view) {

  $results = &$view->result;

  if(is_array($results)) {
   foreach ($results as $key => $result) {
      switch ($view->name) {
        case 'events':
          //Event type
          if(isset($result->field_field_event_type[0]['raw']['tid'])) {
            $event_type_tid = $result->field_field_event_type[0]['raw']['tid'];
            $result->field_field_event_type[0]['raw'] =  _event_finder_api_get_term_data($event_type_tid);
          }   
          // Event Location
          if(isset($result->field_field_location_reference[0]['raw']['target_id'])) {
            $event_location_nid = $result->field_field_location_reference[0]['raw']['target_id'];
            $result->field_field_location_reference[0]['raw'] =  _event_finder_api_get_node_data($event_location_nid);
          }

          break;

          case 'locations': 
          //Location type
          if(isset($result->field_field_location_type[0]['raw']['tid'])) {
            $location_type_tid = $result->field_field_location_type[0]['raw']['tid'];
            $result->field_field_location_type[0]['raw'] =  _event_finder_api_get_term_data($location_type_tid);
          }   

          break;

      }
    }
  }
}


/*
 * Returns a node id and title.
 */ 
function _event_finder_api_get_node_data($nid) {  
  if($nid) {
    $node = node_load($nid);
    $field = array('title' => $node->title, 'nid' => $node->nid);
  }
  return $field;
}

/*
 * Returns term name and term
 */ 
function _event_finder_api_get_term_data($tid) {
  $term = taxonomy_term_load($tid);
  $term_name = $term->name;
  $term_data = array('name' => $term_name , 'tid' => $tid);
  return $term_data;
}

    